### ISSUE TITLE
First time setup, unable to load: "Slack rate limit exceeded, retry after 3s"

### ISSUE THREAD

**Issue by craigotis** [erroneousboat/slack-term#167]
I just installed `slack-term` for the first time on my system using a legacy token. However, upon launching it sits at the `LOADING` screen for 3-4 second, then drops back to the shell with:
```
2018/11/09 16:31:49 Slack rate limit exceeded, retry after 2s
```
My hunch is that the first-time setup is exhausting the API rate limit? But I'm not sure if it's ever going to actually finish:
```
craig@Craigs-MBP-2:~$ slack-term
2018/11/09 16:31:57 Slack rate limit exceeded, retry after 3s
craig@Craigs-MBP-2:~$ slack-term
2018/11/09 16:32:01 Slack rate limit exceeded, retry after 3s
craig@Craigs-MBP-2:~$ slack-term
2018/11/09 16:32:05 Slack rate limit exceeded, retry after 3s
craig@Craigs-MBP-2:~$ slack-term
2018/11/09 16:32:21 Slack rate limit exceeded, retry after 3s
craig@Craigs-MBP-2:~$ slack-term
2018/11/09 16:32:46 Slack rate limit exceeded, retry after 2s
craig@Craigs-MBP-2:~$ slack-term
2018/11/09 16:34:05 Slack rate limit exceeded, retry after 2s
craig@Craigs-MBP-2:~$ slack-term
2018/11/09 16:43:00 Slack rate limit exceeded, retry after 3s
craig@Craigs-MBP-2:~$ slack-term
2018/11/09 16:48:44 Slack rate limit exceeded, retry after 3s
craig@Craigs-MBP-2:~$ slack-term
2018/11/09 16:49:46 Slack rate limit exceeded, retry after 3s
craig@Craigs-MBP-2:~$ slack-term
2018/11/09 16:50:56 Slack rate limit exceeded, retry after 2s
craig@Craigs-MBP-2:~$ slack-term
2018/11/09 16:52:23 Slack rate limit exceeded, retry after 1s
```
Is this a known issue? Something on my end? Is it stuck in a loop somewhere? I can try to Wireshark this if necessary but was hoping for an easier fix.

**Comment by erroneousboat** [comment]
Hmm, it could be that slack-term needs to retrieve a lot of channels and it exceeds the rate limit. Could you perhaps share to what kind of workspace you're connecting, how many channels, users, etc.

**Comment by erroneousboat** [comment]
Yeah, it is likely because of the number of channels/users. Slack-term needs to gather those by issuing several API calls as well figure out the presence of each individual user. In your case it will likely issue too many API calls.

terminal-slack likely uses the 'old' `channels.list` (https://api.slack.com/methods/channels.list). In the past slack-term also used this, and it returned the complete list per type of channel in one go. Now, it is using `conversations.list` (#150, https://api.slack.com/methods/conversations.list).

I'll have a look if it helps to increase the pagination number for requesting channels from the API.

**Comment by craigotis** [comment]
I was able to make the following change and load successfully (as I don't use public channels very often, normally I keep them muted):
```
diff --git a/service/slack.go b/service/slack.go
index 9e82d90..52c6f9a 100644
--- a/service/slack.go
+++ b/service/slack.go
@@ -77,7 +77,6 @@ func (s *SlackService) GetChannels() ([]components.ChannelItem, error) {
                        ExcludeArchived: "true",
                        Limit:           10,
                        Types: []string{
-                               "public_channel",
                                "private_channel",
                                "im",
                                "mpim",
@@ -99,7 +98,6 @@ func (s *SlackService) GetChannels() ([]components.ChannelItem, error) {
                                ExcludeArchived: "true",
                                Limit:           10,
                                Types: []string{
-                                       "public_channel",
                                        "private_channel",
                                        "im",
                                        "mpim",
```
So I think you're definitely right about the public channel/conversation retrieval being the culprit.

Now that I can load successfully, you can probably consider this a low priority, but definitely a nice-to-have, as workspaces only get larger and larger. 😄

**Comment by erroneousboat** [comment]
Cool! Thanks for the heads up. I've pushed a commit on master which increased the pagination limit, and I'm continuing to create a solution for the user presence part, that doesn't make slack-term to wait too long to resolve all the user presence status at startup, and that is able to adhere to the API rate limit.

**Comment by abacao** [comment]
I'm also having this issue.

**Comment by tieoneease** [comment]
I'm still getting this, but my company's workspace probably contains too many channels.

**Comment by abacao** [comment]
Build the "threads" branch and it seems to be working

**Comment by ted-fc** [comment]
@abacao Unfortunately, I'm having this issue in the threads branch as well

**Comment by abacao** [comment]
@ted-fc it's working for me, are you sure you have built the correct branch? Are you sure you are running that exact version?

**Comment by ted-fc** [comment]
I was at the head of threads branch. Is there a specific commit you're referring to?

**Comment by punkdata** [comment]
I'm also having this issue. I can confirm that the Slack workspace I'm connecting to has many channels. I'm running version v0.4.1

Any updates on fixes for this?

**Comment by felippemr** [comment]
I'm using the latest binary available for OSX and still get the rate-limiting problem. What should I do?

**Comment by ddurdle** [comment]
I have the same issue too, on the latest.  I have no idea if this even works as I've never got past the LOADING screen.

**Comment by offlinehoster** [comment]
I just installed the slack-term....got it started for exactly one time....it took a while....and I was logged on...after quitting ad restarting the app I got multiple

```2019/10/24 06:16:19 Slack rate limit exceeded, retry after 1s```

messages. And it does not start any more.

We're running a private slack workspace with many channels, I mean a lot of channels "over 400" and I'm joined to about 50 Channels....

**Comment by jackzzj** [comment]
Still getting this, is this solved ?
